# Generated by Django 5.2.5 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_user_id_central',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID Utilisateur Central (Auth-Service)'),
        ),
    ]
