# Generated by Django 5.2.5 on 2025-09-09 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_legacy', '__first__'),
        ('contrat_chauffeur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_moto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_batt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_paiement', models.DateField()),
                ('methode_paiement', models.CharField(max_length=50)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('type_contrat', models.CharField(max_length=50)),
                ('date_enregistrement', models.DateTimeField()),
                ('statut', models.CharField(max_length=50)),
                ('contrat_chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_lease', to='contrat_chauffeur.contratchauffeur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_agence', models.ForeignKey(db_column='user_agence_id', on_delete=django.db.models.deletion.PROTECT, to='app_legacy.agences')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
