# Generated by Django 5.2.5 on 2025-09-19 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0001_initial'),
        ('paiement_lease', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiementlease',
            name='montant_batt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paiementlease',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiementlease',
            name='user_agence',
            field=models.ForeignKey(db_column='user_agence_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_legacy.agences'),
        ),
    ]
