# Generated by Django 5.2.5 on 2025-09-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_lease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paiementlease',
            table='paiement_lease',
        ),
    ]
