# Generated by Django 5.2.5 on 2025-09-24 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0002_useragences'),
        ('paiement_lease', '0002_alter_paiementlease_employe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiementlease',
            name='user_agence',
            field=models.ForeignKey(blank=True, db_column='user_agence_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_legacy.useragences'),
        ),
    ]
