# Generated by Django 5.2.5 on 2025-09-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0004_usersagences'),
        ('paiement_lease', '0003_alter_paiementlease_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='user_agence',
            field=models.ForeignKey(blank=True, db_column='user_agence_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_legacy.usersagences'),
        ),
    ]
