# Generated by Django 5.2.5 on 2025-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_lease', '0004_alter_paiementlease_user_agence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='date_paiement',
            field=models.DateTimeField(),
        ),
    ]
