# Generated by Django 5.2.5 on 2025-09-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_lease', '0005_alter_paiementlease_date_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementlease',
            name='date_paiement',
        ),
    ]
