# Generated by Django 5.2.5 on 2025-09-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_lease', '0006_remove_paiementlease_date_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='date_concernee',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paiementlease',
            name='date_limite',
            field=models.DateField(),
        ),
    ]
