# Generated by Django 5.2.5 on 2025-10-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0006_agences'),
        ('paiement_lease', '0007_alter_paiementlease_date_concernee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementlease',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='paiementlease',
            name='agences',
            field=models.ForeignKey(blank=True, db_column='agences_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_legacy.agences'),
        ),
    ]
