# Generated by Django 5.2.5 on 2025-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_lease', '0009_alter_paiementlease_montant_batt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementlease',
            name='montant_batt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
