# Generated by Django 5.2.5 on 2025-10-13 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0006_agences'),
        ('contrat_chauffeur', '0021_contratchauffeur_date_modification_statut_and_more'),
        ('paiement_lease', '0010_alter_paiementlease_montant_batt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paiementlease',
            index=models.Index(fields=['contrat_chauffeur', 'date_concernee'], name='paiement_le_contrat_929157_idx'),
        ),
    ]
