# Generated by Django 5.2.5 on 2025-10-29 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_proxym', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frais_transaction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transaction_externe',
            },
        ),
        migrations.CreateModel(
            name='TransactionProxym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('swap', 'Swap'), ('lease', 'Lease'), ('penalite', 'Pénalité')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transaction_proxym',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chauffeur', 'Chauffeur'), ('proxym', 'Proxym'), ('externe', 'Externe')], max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('bloque', 'Bloqué'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='SauvegardeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauvegardes', to='wallet.transaction')),
            ],
            options={
                'db_table': 'sauvegarde_transactions',
            },
        ),
        migrations.CreateModel(
            name='JournalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('maviance', 'Maviance'), ('proxym', 'Proxym'), ('chauffeur', 'Chauffeur')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_transaction_maviance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction')),
                ('id_transaction_chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transactionexterne')),
                ('id_transaction_proxym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transactionproxym')),
            ],
            options={
                'db_table': 'journal_transaction',
            },
        ),
        migrations.AddField(
            model_name='transactionproxym',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_proxym', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transactionexterne',
            name='wallet_envoyeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transactionexterne',
            name='wallet_receveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_maviance', to='wallet.wallet'),
        ),
    ]
