# Generated by Django 5.2.5 on 2025-10-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_journaltransaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
