# Generated by Django 5.2.5 on 2025-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_proxym',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionexterne',
            name='reference',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionproxym',
            name='reference',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
