# Generated by Django 5.2.5 on 2025-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_agences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssociationUserMoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'association_user_motos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotoValide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'moto_valides',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidatedUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'validated_users',
                'managed': False,
            },
        ),
    ]
