# Generated by Django 5.2.5 on 2025-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_agences',
            },
        ),
        migrations.CreateModel(
            name='AssociationUserMoto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'association_user_moto',
            },
        ),
    ]
