# Generated by Django 5.2.5 on 2025-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgences',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_agences',
                'managed': False,
            },
        ),
    ]
