# Generated by Django 5.2.5 on 2025-09-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agences',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='associationusermoto',
            options={'managed': False},
        ),
    ]
