# Generated by Django 5.2.5 on 2025-09-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0002_useragences'),
        ('paiement_lease', '0003_alter_paiementlease_employe_and_more'),
        ('penalite', '0003_remove_penalite_date_creation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agences',
        ),
        migrations.AlterModelTable(
            name='motovalide',
            table='motos_valides',
        ),
    ]
