# Generated by Django 5.2.5 on 2025-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0003_delete_agences_alter_motovalide_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAgences',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_agences',
                'managed': False,
            },
        ),
    ]
