# Generated by Django 5.2.5 on 2025-09-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0004_usersagences'),
        ('paiement_lease', '0004_alter_paiementlease_user_agence'),
        ('penalite', '0004_alter_paiementpenalite_user_agence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgences',
        ),
    ]
