# Generated by Django 5.2.5 on 2025-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0005_delete_useragences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_agence', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'agences',
                'managed': False,
            },
        ),
    ]
