# Generated by Django 5.2.5 on 2025-10-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0006_agences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validateduser',
            options={'managed': True},
        ),
    ]
