# Generated by Django 5.2.5 on 2025-10-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0007_alter_validateduser_options'),
        ('wallet', '0004_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validateduser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validateduser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validateduser',
            name='user_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validateduser',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_user', to='wallet.wallet'),
        ),
    ]
