# Generated by Django 5.2.5 on 2025-10-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0008_validateduser_email_validateduser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validateduser',
            options={'managed': False},
        ),
    ]
