# Generated by Django 5.2.5 on 2025-09-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_legacy', '0001_initial'),
        ('garant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratBatterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_signature', models.DateField()),
                ('date_enregistrement', models.DateField()),
                ('date_debut', models.DateField()),
                ('duree_jour', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_engage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_caution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('chauffeur_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_batteries', to='app_legacy.associationusermoto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('montant_restant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('frequence_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_par_paiement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('duree_jour', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_engage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('contrat_physique_chauffeur', models.CharField(blank=True, max_length=255, null=True)),
                ('contrat_physique_batt', models.CharField(blank=True, max_length=255, null=True)),
                ('contrat_physique_moto_garant', models.CharField(blank=True, max_length=255, null=True)),
                ('contrat_physique_batt_garant', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_caution_batt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('montant_engage_batt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True)),
                ('duree_caution_batt', models.DateField(blank=True, null=True)),
                ('jour_conge_total', models.IntegerField(blank=True, default=0, null=True)),
                ('jour_conge_utilise', models.IntegerField(blank=True, default=0, null=True)),
                ('jour_conge_restant', models.IntegerField(blank=True, default=0, null=True)),
                ('association_user_moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_chauffeur', to='app_legacy.associationusermoto')),
                ('contrat_batt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_chauffeur', to='contrat_chauffeur.contratbatterie')),
                ('garant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_garantis', to='garant.garant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
