# Generated by Django 5.2.5 on 2025-09-09 15:35

import contrat_chauffeur.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_legacy', '__first__'),
        ('garant', '0002_garant_cni_recto_garant_cni_verso_and_more'),
        ('penalite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratBatterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_signature', models.DateField()),
                ('date_enregistrement', models.DateField()),
                ('date_debut', models.DateField()),
                ('duree_jour', models.IntegerField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_engage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('montant_caution', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'contrat_batterie',
            },
        ),
        migrations.CreateModel(
            name='ContratChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference_contrat', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('frequence_paiement', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('biweekly', 'Bimensuel'), ('monthly', 'Mensuel'), ('custom', 'Personnalisé')], default='weekly', max_length=50)),
                ('montant_par_paiement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('duree_jour', models.PositiveIntegerField(blank=True, help_text='Durée du contrat en jours', null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('terminated', 'Résilié'), ('completed', 'Terminé')], default='active', max_length=50)),
                ('montant_engage', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contrat_physique_chauffeur', models.FileField(blank=True, null=True, upload_to=contrat_chauffeur.models.contract_upload_path)),
                ('contrat_physique_batt', models.FileField(blank=True, null=True, upload_to=contrat_chauffeur.models.contract_upload_path)),
                ('contrat_physique_moto_garant', models.FileField(blank=True, null=True, upload_to=contrat_chauffeur.models.contract_upload_path)),
                ('contrat_physique_batt_garant', models.FileField(blank=True, null=True, upload_to=contrat_chauffeur.models.contract_upload_path)),
                ('montant_caution_batt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_engage_batt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('duree_caution_batt', models.DateField(blank=True, null=True)),
                ('jour_conge_total', models.PositiveIntegerField(default=0)),
                ('jour_conge_utilise', models.PositiveIntegerField(default=0)),
                ('jour_conge_restant', models.PositiveIntegerField(default=0, editable=False)),
                ('association_user_moto', models.ForeignKey(db_column='association_user_moto_id', on_delete=django.db.models.deletion.PROTECT, related_name='contrats_chauffeur', to='app_legacy.associationusermoto')),
                ('contrat_batt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_chauffeur', to='contrat_chauffeur.contratbatterie')),
                ('garant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_chauffeur', to='garant.garant')),
                ('regle_penalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_chauffeur', to='penalite.reglepenalite')),
            ],
            options={
                'db_table': 'contrat_chauffeur',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['statut', 'date_fin'], name='contrat_cha_statut_4094be_idx'), models.Index(fields=['garant', 'statut'], name='contrat_cha_garant__1752e4_idx'), models.Index(fields=['association_user_moto_id', 'statut'], name='contrat_cha_associa_7423b7_idx')],
            },
        ),
    ]
