# Generated by Django 5.2.5 on 2025-09-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat_chauffeur', '0001_initial'),
        ('penalite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratchauffeur',
            name='regle_penalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='penalite.reglepenalite'),
        ),
    ]
