# Generated by Django 5.2.5 on 2025-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratbatterie',
            name='contrat_physique_batt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
