# Generated by Django 5.2.5 on 2025-09-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0002_contratbatterie_contrat_physique_batt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratbatterie',
            name='date_enregistrement',
        ),
    ]
