# Generated by Django 5.2.5 on 2025-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0003_remove_contratbatterie_date_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='frequence_paiement',
        ),
    ]
