# Generated by Django 5.2.5 on 2025-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0004_remove_contratchauffeur_frequence_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='contrat_physique_batt',
        ),
    ]
