# Generated by Django 5.2.5 on 2025-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0005_remove_contratchauffeur_contrat_physique_batt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='duree_caution_batt',
        ),
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='montant_caution_batt',
        ),
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='montant_engage_batt',
        ),
    ]
