# Generated by Django 5.2.5 on 2025-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0006_remove_contratchauffeur_duree_caution_batt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratbatterie',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
