# Generated by Django 5.2.5 on 2025-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0007_contratbatterie_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
