# Generated by Django 5.2.5 on 2025-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0008_alter_contratchauffeur_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='statut',
            field=models.CharField(choices=[('encours', 'En cours'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='encours', max_length=50),
        ),
    ]
