# Generated by Django 5.2.5 on 2025-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0009_alter_contratchauffeur_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratbatterie',
            name='statut',
            field=models.CharField(blank=True, default='encours', max_length=50, null=True),
        ),
    ]
