# Generated by Django 5.2.5 on 2025-09-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0010_alter_contratbatterie_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratchauffeur',
            name='date_enregistrement',
        ),
    ]
