# Generated by Django 5.2.5 on 2025-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0011_remove_contratchauffeur_date_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratchauffeur',
            name='date_concernee',
            field=models.DateTimeField(default='2025-09-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateTimeField(default='2025-09-19'),
            preserve_default=False,
        ),
    ]
