# Generated by Django 5.2.5 on 2025-09-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0013_alter_contratchauffeur_date_concernee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratbatterie',
            name='montant_par_paiement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
