# Generated by Django 5.2.5 on 2025-09-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0014_contratbatterie_montant_par_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratbatterie',
            name='montant_caution',
        ),
    ]
