# Generated by Django 5.2.5 on 2025-09-24 14:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0015_remove_contratbatterie_montant_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_concernee',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 14, 39, 47, 447308, tzinfo=datetime.timezone.utc)),
        ),
    ]
