# Generated by Django 5.2.5 on 2025-09-24 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0016_alter_contratchauffeur_date_concernee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2025, 9, 25, 16, 9, 14, 867006, tzinfo=datetime.timezone.utc)),
        ),
    ]
