# Generated by Django 5.2.5 on 2025-09-25 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0017_alter_contratchauffeur_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2025, 9, 26, 16, 32, 43, 666006, tzinfo=datetime.timezone.utc)),
        ),
    ]
