# Generated by Django 5.2.5 on 2025-09-29 09:39

import contrat_chauffeur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0018_alter_contratchauffeur_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_concernee',
            field=models.DateField(default=contrat_chauffeur.models.default_date_concernee),
        ),
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateField(default=contrat_chauffeur.models.default_date_limite),
        ),
    ]
