# Generated by Django 5.2.5 on 2025-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0019_alter_contratchauffeur_date_concernee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_concernee',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contratchauffeur',
            name='date_limite',
            field=models.DateField(null=True),
        ),
    ]
