# Generated by Django 5.2.5 on 2025-10-06 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0020_alter_contratchauffeur_date_concernee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratchauffeur',
            name='date_modification_statut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification du statut'),
        ),
        migrations.AddField(
            model_name='contratchauffeur',
            name='motif_modification_statut',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du changement de statut'),
        ),
        migrations.AddField(
            model_name='contratchauffeur',
            name='statut_modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Employé ayant modifié le statut'),
        ),
    ]
