# Generated by Django 5.2.5 on 2025-09-09 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_legacy', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type_penalite', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_creation', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(max_length=50)),
                ('date_payement_manquee', models.DateField(blank=True, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglePenalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('heure_min', models.TimeField(blank=True, null=True)),
                ('heure_max', models.TimeField(blank=True, null=True)),
                ('montant_leger_moto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_grave_moto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_leger_batt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_grave_batt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_regle', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaiementPenalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100)),
                ('date_paiement', models.DateTimeField()),
                ('methode_paiement', models.CharField(max_length=50)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_agence', models.ForeignKey(db_column='user_agence_id', on_delete=django.db.models.deletion.PROTECT, to='app_legacy.agences')),
                ('penalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='penalite.penalite')),
            ],
            options={
                'db_table': 'paiement_penalite',
            },
        ),
    ]
