# Generated by Django 5.2.5 on 2025-09-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0002_contratbatterie_contrat_physique_batt'),
        ('penalite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='contrat_chauffeur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='contrat_chauffeur.contratchauffeur'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='penalite',
            table='penalite',
        ),
    ]
