# Generated by Django 5.2.5 on 2025-09-04 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0002_alter_agences_options_and_more'),
        ('contrat_chauffeur', '0001_initial'),
        ('penalite', '0002_penalite_contrat_chauffeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiementpenalite',
            old_name='employe_id',
            new_name='employe',
        ),
        migrations.RemoveField(
            model_name='paiementpenalite',
            name='user_agence_id',
        ),
        migrations.AddField(
            model_name='paiementpenalite',
            name='user_agence',
            field=models.ForeignKey(db_column='user_agence_id', default='', on_delete=django.db.models.deletion.PROTECT, to='app_legacy.agences'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalite',
            name='contrat_chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='contrat_chauffeur.contratchauffeur'),
        ),
    ]
