# Generated by Django 5.2.5 on 2025-09-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0002_useragences'),
        ('penalite', '0002_penalite_contrat_chauffeur_alter_penalite_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalite',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='paiementpenalite',
            name='user_agence',
            field=models.ForeignKey(db_column='user_agence_id', on_delete=django.db.models.deletion.PROTECT, to='app_legacy.useragences'),
        ),
    ]
