# Generated by Django 5.2.5 on 2025-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0004_alter_paiementpenalite_user_agence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penalite',
            old_name='date_payement_manquee',
            new_name='date_paiement_manquee',
        ),
        migrations.RenameField(
            model_name='penalite',
            old_name='montant',
            new_name='montant_penalite',
        ),
        migrations.RenameField(
            model_name='penalite',
            old_name='motif',
            new_name='motif_penalite',
        ),
        migrations.RenameField(
            model_name='penalite',
            old_name='statut',
            new_name='statut_penalite',
        ),
        migrations.RemoveField(
            model_name='paiementpenalite',
            name='date_paiement',
        ),
        migrations.AddField(
            model_name='paiementpenalite',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
