# Generated by Django 5.2.5 on 2025-09-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_legacy', '0005_delete_useragences'),
        ('penalite', '0005_rename_date_payement_manquee_penalite_date_paiement_manquee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementpenalite',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiementpenalite',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paiementpenalite',
            name='user_agence',
            field=models.ForeignKey(blank=True, db_column='user_agence_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_legacy.usersagences'),
        ),
    ]
