# Generated by Django 5.2.5 on 2025-09-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0018_alter_contratchauffeur_date_limite'),
        ('penalite', '0006_alter_paiementpenalite_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalite',
            name='type_penalite',
            field=models.CharField(choices=[('legere', 'Légère'), ('grave', 'Grave')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.UniqueConstraint(fields=('contrat_chauffeur', 'date_paiement_manquee', 'type_penalite'), name='uniq_penalite_par_contrat_jour_et_type'),
        ),
    ]
