# Generated by Django 5.2.5 on 2025-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0007_alter_penalite_type_penalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='echeance_paiement_penalite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
