# Generated by Django 5.2.5 on 2025-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0008_penalite_echeance_paiement_penalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalite',
            name='echeance_paiement_penalite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
