# Generated by Django 5.2.5 on 2025-10-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0009_alter_penalite_echeance_paiement_penalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalite',
            name='date_limite_reference',
            field=models.DateField(blank=True, null=True),
        ),
    ]
