# Generated by Django 5.2.5 on 2025-10-02 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0020_alter_contratchauffeur_date_concernee_and_more'),
        ('penalite', '0010_penalite_date_limite_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalite',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='penalite',
            name='annulee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalites_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalite',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalite',
            name='justificatif_annulation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='penalite',
            name='statut_penalite',
            field=models.CharField(choices=[('non_paye', 'Non payé'), ('partiellement_paye', 'Partiellement payé'), ('paye', 'Payé'), ('annulee', 'Annulée')], default='non_paye', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut_penalite', 'annulee'), _negated=True), ('type_penalite', 'legere'), _connector='OR'), name='penalite_annulee_uniquement_si_legere'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut_penalite', 'annulee'), _negated=True), models.Q(('justificatif_annulation', ''), _negated=True), _connector='OR'), name='penalite_annulee_justificatif_obligatoire'),
        ),
        migrations.AddConstraint(
            model_name='penalite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut_penalite', 'annulee'), _negated=True), ('montant_paye', 0), _connector='OR'), name='penalite_annulee_montant_paye_zero'),
        ),
    ]
