# Generated by Django 5.2.5 on 2025-10-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0011_alter_penalite_options_penalite_annulee_par_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reglepenalite',
            table='penalite_regle',
        ),
    ]
