# Generated by Django 5.2.5 on 2025-10-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalite', '0012_alter_reglepenalite_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penalite',
            name='penalite_annulee_uniquement_si_legere',
        ),
    ]
