# Generated by Django 5.2.5 on 2025-10-13 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat_chauffeur', '0021_contratchauffeur_date_modification_statut_and_more'),
        ('penalite', '0013_remove_penalite_penalite_annulee_uniquement_si_legere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='penalite',
            index=models.Index(fields=['contrat_chauffeur', 'date_paiement_manquee'], name='penalite_contrat_8bdb0e_idx'),
        ),
    ]
