# Generated by Django 5.2.5 on 2025-09-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrat_chauffeur', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(max_length=50)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='contrat_chauffeur.contratchauffeur')),
            ],
            options={
                'db_table': 'conge',
            },
        ),
    ]
