# Generated by Django 5.2.5 on 2025-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='date_reprise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='conge',
            name='nb_jours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
