# Generated by Django 5.2.5 on 2025-09-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conge', '0001_initial'),
        ('contrat_chauffeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='contrat_chauffeur.contratchauffeur'),
        ),
    ]
