# Generated by Django 5.2.5 on 2025-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0002_conge_date_reprise_conge_nb_jours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('annule', 'Annulé'), ('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('termine', 'Terminé'), ('rejete', 'Rejeté'), ('en_cours', 'En cours')], default='en_attente', max_length=50),
        ),
    ]
