# Generated by Django 5.2.5 on 2025-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0003_alter_conge_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='motif_conge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
