# Generated by Django 5.2.5 on 2025-09-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0004_conge_motif_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='motif_conge',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
