# Generated by Django 5.2.5 on 2025-09-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0005_alter_conge_motif_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='statut',
            field=models.CharField(choices=[('annule', 'Annulé'), ('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('termine', 'Terminé'), ('rejete', 'Rejeté')], default='en_attente', max_length=50),
        ),
    ]
