# Generated by Django 5.2.5 on 2025-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0006_alter_conge_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conge',
            old_name='nb_jours',
            new_name='nb_jour',
        ),
    ]
