# Generated by Django 5.2.5 on 2025-10-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0007_rename_nb_jours_conge_nb_jour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ('-created',)},
        ),
    ]
