# Generated by Django 5.2.5 on 2025-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0008_alter_conge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='date_reprise',
            field=models.DateField(null=True),
        ),
    ]
